# Generated by Django 4.2.7 on 2026-01-17 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('delay_hours', models.IntegerField()),
                ('total_passengers', models.IntegerField()),
                ('vip_passengers', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='agents_flig_created_687b18_idx'), models.Index(fields=['flight_number'], name='agents_flig_flight__5adc20_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='agents_agen_created_5f530f_idx'), models.Index(fields=['agent_name'], name='agents_agen_agent_n_e5a932_idx')],
            },
        ),
    ]
