# Generated by Django 4.2.7 on 2026-01-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
